# Start here!
services:
  db:
    container_name: wheel-project-db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wheelnet

  server:
    container_name: wheel-project-server
    image: ghcr.io/minjaekimmm/wheel-project:latest
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_CLOUDFRONT=${AWS_S3_CLOUDFRONT}
    networks:
      - wheelnet
    depends_on:
      - db

  nginx:
    container_name: wheel-project-nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wheelnet
    depends_on:
      - server

networks:
  wheelnet:

volumes:
  db-data:

